# Generated by Django 4.2.18 on 2025-01-31 13:41

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConcertPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("date", models.DateField()),
                ("artist", models.CharField(max_length=100)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("description", models.TextField(blank=True, null=True)),
                ("genre", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="SeatZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Zone name (e.g., Front Zone)", max_length=100
                    ),
                ),
                (
                    "row_start",
                    models.CharField(
                        help_text="Starting row (e.g., A)", max_length=1, null=True
                    ),
                ),
                (
                    "row_end",
                    models.CharField(
                        help_text="Ending row (e.g., D)", max_length=1, null=True
                    ),
                ),
                (
                    "seat_start",
                    models.PositiveIntegerField(
                        help_text="Starting seat number (e.g., 1)", null=True
                    ),
                ),
                (
                    "seat_end",
                    models.PositiveIntegerField(
                        help_text="Last seat number (e.g., 10)", null=True
                    ),
                ),
                ("slug", models.SlugField(null=True)),
                ("capacity", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VenuePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "admission_mode",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned Seating Only"),
                            ("general", "General Admission Only"),
                            ("mixed", "Both Assigned and General Admission"),
                        ],
                        default="assigned",
                        help_text="Allowed admission types for this venue",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(help_text="Venue name", max_length=100)),
                ("address", models.TextField(help_text="Venue address")),
                ("capacity", models.IntegerField(help_text="Total seating capacity")),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="TicketType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned Seating"),
                            ("general", "General Admission"),
                        ],
                        max_length=10,
                    ),
                ),
                ("slug", models.SlugField(null=True)),
                (
                    "ga_capacity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum tickets for general admission",
                        null=True,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sold", models.PositiveIntegerField(default=0)),
                (
                    "concert",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_types",
                        to="api.concertpage",
                    ),
                ),
                (
                    "seat_zone",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required for assigned seating tickets",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.seatzone",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="seatzone",
            name="venue",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seat_zones",
                to="api.venuepage",
            ),
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row", models.CharField(max_length=1)),
                ("number", models.PositiveIntegerField()),
                ("identifier", models.CharField(max_length=10)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="api.seatzone",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="concertpage",
            name="venue",
            field=models.ForeignKey(
                help_text="Select the venue for this concert",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="concerts",
                to="api.venuepage",
            ),
        ),
        migrations.CreateModel(
            name="SoldSeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "concert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sold_seats",
                        to="api.concertpage",
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.seat"
                    ),
                ),
            ],
            options={
                "unique_together": {("concert", "seat")},
            },
        ),
    ]
