# Generated by Django 4.2.18 on 2025-01-28 07:29

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0027_image_description"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConcertIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("location", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", wagtail.fields.RichTextField(blank=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("concert_type", models.CharField(max_length=100)),
                ("artist", models.CharField(max_length=100)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("ticket_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("seat", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=100)),
                ("purchase_date", models.DateField()),
                ("purchase_time", models.TimeField()),
                ("quantity", models.IntegerField()),
                (
                    "concert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="api.concertindexpage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoogleSheetUpdateMeta",
            fields=[
                ("sheet_id", models.AutoField(primary_key=True, serialize=False)),
                ("sheet_name", models.CharField(max_length=100)),
                ("action", models.CharField(max_length=100)),
                ("modified_date", models.DateField()),
                ("modified_time", models.TimeField()),
                (
                    "concert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sheet_updates",
                        to="api.concertindexpage",
                    ),
                ),
            ],
        ),
    ]
