# Generated by Django 4.2.18 on 2025-02-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seatzone",
            name="type",
            field=models.CharField(default="assigned", max_length=10),
        ),
    ]
