# Generated by Django 4.2.18 on 2025-02-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_seatzone_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="seatzone",
            name="total_seats",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
